apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onlineboutique
  namespace: shop
spec:
  chart:
    spec:
      version: ">=0.10.0"
  values:
    networkPolicies:
      create: false
    frontend:
      externalService: false
    loadGenerator:
      create: false
      name: loadgenerator
      checkFrontendInitContainer: true
      resources:
        requests:
          cpu: 300m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    