apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onlineboutique
  namespace: shop
spec:
  timeout: 15m
  chart:
    spec:
      version: ">=0.10.0"
  values:
    networkPolicies:
      create: false
    seccompProfile:
      enable: true
      type: RuntimeDefault
    frontend:
      externalService: false
    loadGenerator:
      create: true
      name: loadgenerator
      checkFrontendInitContainer: false
      resources:
        requests:
          cpu: 300m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    