apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onlineboutique
  namespace: shop
spec:
  interval: 10m
  type: oci
  url: oci://us-docker.pkg.dev/online-boutique-ci/charts